export const VIEW_VOICE_NOTE_MODAL = 'VIEW_VOICE_NOTE_MODAL'
export const HIDE_VOICE_NOTE_MODAL = 'HIDE_VOICE_NOTE_MODAL'

export const VIEW_FU_MODAL = 'VIEW_FU_MODAL'
export const HIDE_FU_MODAL = 'HIDE_FU_MODAL'
