export const ADD_NODE = 'ADD_NODE'
export const ADD_NODE_BROADCAST = 'ADD_NODE_BROADCAST'
export const UPDATE_POS = 'UPDATE_POS'

export const ON_CONNECT_SEND = 'ON_CONNECT_SEND'
export const ON_CONNECT_RECEIVE = 'ON_CONNECT_RECEIVE'

export const REMOVE_NODE = 'REMOVE_NODE'
export const REMOVE_NODE_BROADCAST = 'REMOVE_NODE_BROADCAST'
